Raw json:

{'hasError': True, 'errParameter': ['dfs.namenode.name.dir', 'dfs.namenode.max.objects', 'dfs.client.datanode-restart.timeout'], 'reason': ['The value of dfs.namenode.name.dir is invalid.', 'The value of dfs.namenode.max.objects is invalid.', 'The value of dfs.client.datanode-restart.timeout is invalid.']}

Final result:

There are 3 misconfiguration parameters in the input: dfs.namenode.name.dir	dfs.namenode.max.objects	dfs.client.datanode-restart.timeout
[Ciri] Reason for dfs.namenode.name.dir: The value of dfs.namenode.name.dir is invalid.
[Ciri] Reason for dfs.namenode.max.objects: The value of dfs.namenode.max.objects is invalid.
[Ciri] Reason for dfs.client.datanode-restart.timeout: The value of dfs.client.datanode-restart.timeout is invalid.
