Raw json:

{'hasError': True, 'errParameter': ['alluxio.user.file.replication.max', 'alluxio.master.metadata.sync.ufs.prefetch.pool.size', 'alluxio.master.embedded.journal.retry.cache.expiry.time', 'alluxio.user.network.rpc.max.inbound.message.size', 'alluxio.zookeeper.leader.inquiry.retry', 'alluxio.user.network.rpc.flowcontrol.window', 'alluxio.master.ufs.path.cache.capacity'], 'reason': ['Invalid value for alluxio.user.file.replication.max. It should be a positive integer or -1 for unlimited.', 'Invalid value for alluxio.master.metadata.sync.ufs.prefetch.pool.size. It should be a positive integer.', 'Invalid format for alluxio.master.embedded.journal.retry.cache.expiry.time. It should be in milliseconds.', 'Invalid value for alluxio.user.network.rpc.max.inbound.message.size. It should be specified in bytes.', 'Invalid value for alluxio.zookeeper.leader.inquiry.retry. It should be a positive integer.', 'Invalid value for alluxio.user.network.rpc.flowcontrol.window. It should be specified in bytes.', 'Invalid value for alluxio.master.ufs.path.cache.capacity. It should be a positive integer.']}

{'hasError': True, 'errParameter': ['alluxio.user.file.replication.max', 'alluxio.master.metadata.sync.ufs.prefetch.pool.size', 'alluxio.master.embedded.journal.retry.cache.expiry.time', 'alluxio.user.network.rpc.max.inbound.message.size', 'alluxio.zookeeper.leader.inquiry.retry', 'alluxio.user.network.rpc.flowcontrol.window', 'alluxio.master.ufs.path.cache.capacity'], 'reason': ["Invalid value for 'alluxio.user.file.replication.max'. It should be a positive integer or -1 for unlimited.", "Invalid value for 'alluxio.master.metadata.sync.ufs.prefetch.pool.size'. It should be a positive integer.", "Invalid format for 'alluxio.master.embedded.journal.retry.cache.expiry.time'. It should be in milliseconds.", "Invalid value for 'alluxio.user.network.rpc.max.inbound.message.size'. It should be in bytes.", "Invalid value for 'alluxio.zookeeper.leader.inquiry.retry'. It should be a positive integer.", "Invalid value for 'alluxio.user.network.rpc.flowcontrol.window'. It should be in bytes.", "Invalid value for 'alluxio.master.ufs.path.cache.capacity'. It should be a positive integer."]}

{'hasError': False, 'errParameter': [], 'reason': []}

Final result:

There are 7 misconfiguration parameters in the input: alluxio.user.file.replication.max	alluxio.master.metadata.sync.ufs.prefetch.pool.size	alluxio.master.embedded.journal.retry.cache.expiry.time	alluxio.user.network.rpc.max.inbound.message.size	alluxio.zookeeper.leader.inquiry.retry	alluxio.user.network.rpc.flowcontrol.window	alluxio.master.ufs.path.cache.capacity
[Ciri] Reason for alluxio.user.file.replication.max: Invalid value for 'alluxio.user.file.replication.max'. It should be a positive integer or -1 for unlimited.
[Ciri] Reason for alluxio.master.metadata.sync.ufs.prefetch.pool.size: Invalid value for 'alluxio.master.metadata.sync.ufs.prefetch.pool.size'. It should be a positive integer.
[Ciri] Reason for alluxio.master.embedded.journal.retry.cache.expiry.time: Invalid format for 'alluxio.master.embedded.journal.retry.cache.expiry.time'. It should be in milliseconds.
[Ciri] Reason for alluxio.user.network.rpc.max.inbound.message.size: Invalid value for alluxio.user.network.rpc.max.inbound.message.size. It should be specified in bytes.
[Ciri] Reason for alluxio.zookeeper.leader.inquiry.retry: Invalid value for 'alluxio.zookeeper.leader.inquiry.retry'. It should be a positive integer.
[Ciri] Reason for alluxio.user.network.rpc.flowcontrol.window: Invalid value for 'alluxio.user.network.rpc.flowcontrol.window'. It should be in bytes.
[Ciri] Reason for alluxio.master.ufs.path.cache.capacity: Invalid value for 'alluxio.master.ufs.path.cache.capacity'. It should be a positive integer.
