Wrong shot number:
[6, 3, 5]

Correct shot number:
[1]

Raw json:

{'hasError': True, 'errParameter': ['USE_DEPRECATED_PYTZ', 'FILE_UPLOAD_MAX_MEMORY_SIZE'], 'reason': ["The property 'USE_DEPRECATED_PYTZ' is no longer supported in Django 4.0.", "The property 'FILE_UPLOAD_MAX_MEMORY_SIZE' is defined multiple times with different values."]}

{'hasError': True, 'errParameter': ['USE_DEPRECATED_PYTZ', 'FILE_UPLOAD_MAX_MEMORY_SIZE'], 'reason': ["The property 'USE_DEPRECATED_PYTZ' is no longer used in Django 4.0.", "The property 'FILE_UPLOAD_MAX_MEMORY_SIZE' is duplicated in the configuration file."]}

{'hasError': True, 'errParameter': ['USE_DEPRECATED_PYTZ', 'FILE_UPLOAD_MAX_MEMORY_SIZE'], 'reason': ["The property 'USE_DEPRECATED_PYTZ' is no longer supported in Django 4.0.", "The property 'FILE_UPLOAD_MAX_MEMORY_SIZE' has a value of '5242880' which exceeds the default maximum value. It should be within the accepted range."]}

Final result:

There are 2 misconfiguration parameters in the input: USE_DEPRECATED_PYTZ	FILE_UPLOAD_MAX_MEMORY_SIZE
[Ciri] Reason for USE_DEPRECATED_PYTZ: The property 'USE_DEPRECATED_PYTZ' is no longer supported in Django 4.0.
[Ciri] Reason for FILE_UPLOAD_MAX_MEMORY_SIZE: The property 'FILE_UPLOAD_MAX_MEMORY_SIZE' is duplicated in the configuration file.
