Raw json:

{'hasError': True, 'errParameter': ['dfs.datanode.http.internal-proxy.port'], 'reason': ["The value for 'dfs.datanode.http.internal-proxy.port' should be an integer representing the port number, but it is set to 'file://', which is incorrect."]}

Final result:

There are 1 misconfiguration parameters in the input: dfs.datanode.http.internal-proxy.port
[Ciri] Reason for dfs.datanode.http.internal-proxy.port: The value for 'dfs.datanode.http.internal-proxy.port' should be an integer representing the port number, but it is set to 'file://', which is incorrect.
