Raw json:

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase'], 'reason': ['The value of alluxio.user.client.cache.evictor.lfu.logbase is not a valid number. Please check the value of this property.']}

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase', 'alluxio.user.metadata.cache.max.size', 'alluxio.worker.keytab.file'], 'reason': ['The value of alluxio.user.client.cache.evictor.lfu.logbase is not a valid number', 'The value of alluxio.user.metadata.cache.max.size is not a valid number', 'The value of alluxio.worker.keytab.file is not a valid file']}

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase', 'alluxio.user.metadata.cache.max.size', 'alluxio.worker.keytab.file', 'alluxio.zookeeper.session.timeout', 'alluxio.underfs.gcs.version'], 'reason': ['alluxio.user.client.cache.evictor.lfu.logbase must be a positive integer', 'alluxio.user.metadata.cache.max.size must be a positive integer', 'alluxio.worker.keytab.file must be a valid file path', 'alluxio.zookeeper.session.timeout must be a valid duration', 'alluxio.underfs.gcs.version must be a valid version']}

Raw json:

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase', 'alluxio.user.metadata.cache.max.size', 'alluxio.worker.keytab.file'], 'reason': ['alluxio.user.client.cache.evictor.lfu.logbase must be a positive integer', 'alluxio.user.metadata.cache.max.size must be a positive integer', 'alluxio.worker.keytab.file must be a valid file path']}

{'hasError': True, 'errParameter': ['alluxio.user.metadata.cache.max.size', 'alluxio.user.client.cache.evictor.lfu.logbase'], 'reason': ['alluxio.user.metadata.cache.max.size should be a positive integer', 'alluxio.user.client.cache.evictor.lfu.logbase should be a positive number']}

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase'], 'reason': ['alluxio.user.client.cache.evictor.lfu.logbase must be a positive integer']}

Raw json:

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase'], 'reason': ['The value of alluxio.user.client.cache.evictor.lfu.logbase is not a valid number.']}

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase', 'alluxio.worker.keytab.file'], 'reason': ['The value of alluxio.user.client.cache.evictor.lfu.logbase should be a positive integer.', 'The value of alluxio.worker.keytab.file should be a valid file path.']}

{'hasError': True, 'errParameter': ['alluxio.user.client.cache.evictor.lfu.logbase'], 'reason': ['alluxio.user.client.cache.evictor.lfu.logbase should be a positive integer']}

Final result:

There are 1 misconfiguration parameters in the input: alluxio.user.client.cache.evictor.lfu.logbase
[Ciri] Reason for alluxio.user.client.cache.evictor.lfu.logbase: The value of alluxio.user.client.cache.evictor.lfu.logbase is not a valid number.
