Wrong shot number:
[8, 1, 12]

Correct shot number:
[11]

Raw json:

{'hasError': True, 'errParameter': ['alluxio.underfs.s3.connection.ttl'], 'reason': ["The property 'alluxio.underfs.s3.connection.ttl' has the value '-2' which is not within the accepted value [0, 1000000]."]}

{'hasError': True, 'errParameter': ['alluxio.underfs.s3.connection.ttl'], 'reason': ["The property 'alluxio.underfs.s3.connection.ttl' has the value '-2' which is not within the accepted value [0, 2147483647]."]}

{'hasError': True, 'errParameter': ['alluxio.underfs.s3.connection.ttl'], 'reason': ["The property 'alluxio.underfs.s3.connection.ttl' has the value '-2' which is less than the minimum allowed value 0."]}

Final result:

There are 1 misconfiguration parameters in the input: alluxio.underfs.s3.connection.ttl
[Ciri] Reason for alluxio.underfs.s3.connection.ttl: The property 'alluxio.underfs.s3.connection.ttl' has the value '-2' which is not within the accepted value [0, 1000000].
