Raw json:

{'hasError': True, 'errParameter': ['fs.ftp.host.port', 'fs.s3a.retry.throttle.limit', 'hadoop.caller.context.signature.max.size'], 'reason': ['fs.ftp.host.port is not a valid port number.', 'fs.s3a.retry.throttle.limit is not a valid number.', 'hadoop.caller.context.signature.max.size is not a valid number.']}

Final result:

There are 3 misconfiguration parameters in the input: fs.ftp.host.port	fs.s3a.retry.throttle.limit	hadoop.caller.context.signature.max.size
[Ciri] Reason for fs.ftp.host.port: fs.ftp.host.port is not a valid port number.
[Ciri] Reason for fs.s3a.retry.throttle.limit: fs.s3a.retry.throttle.limit is not a valid number.
[Ciri] Reason for hadoop.caller.context.signature.max.size: hadoop.caller.context.signature.max.size is not a valid number.
