Raw json:

{'hasError': True, 'errParameter': ['hadoop.security.group.mapping.ldap.read.timeout.ms'], 'reason': ['The value of hadoop.security.group.mapping.ldap.read.timeout.ms is not a valid integer.']}

{'hasError': True, 'errParameter': ['hadoop.security.group.mapping.ldap.read.timeout.ms'], 'reason': ['The value of hadoop.security.group.mapping.ldap.read.timeout.ms is not a positive integer.']}

{'hasError': True, 'errParameter': ['hadoop.security.group.mapping.ldap.read.timeout.ms', 'fs.s3a.s3guard.ddb.table.capacity.write', 'ipc.client.kill.max', 'ipc.client.low-latency', 'ftp.client-write-packet-size'], 'reason': ['The value of hadoop.security.group.mapping.ldap.read.timeout.ms is not a valid integer.', 'The value of fs.s3a.s3guard.ddb.table.capacity.write is not a valid integer.', 'The value of ipc.client.kill.max is not a valid integer.', 'The value of ipc.client.low-latency is not a valid boolean.', 'The value of ftp.client-write-packet-size is not a valid integer.']}

Final result:

There are 1 misconfiguration parameters in the input: hadoop.security.group.mapping.ldap.read.timeout.ms
[Ciri] Reason for hadoop.security.group.mapping.ldap.read.timeout.ms: The value of hadoop.security.group.mapping.ldap.read.timeout.ms is not a positive integer.
